[package]
name = "libjpeg-sys"
description = "Builds and links libjpeg(-turbo)"
version = "0.1.0"
edition = "2021"
license = "MIT"
links = "jpeg"

[lib]
name = "jpeg"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
anyhow = "1.0.75"
cmake = "0.1.50"

[features]
