[package]
name = "libjpeg-sys"
description = "Builds and links libjpeg(-turbo)"
version = "0.1.0"
edition = "2021"
license = "MIT"
links = "libjpeg"

[dependencies]

[build-dependencies]
cc = "1.0.73"
cmake = { version = "0.1.48", optional = true }
bindgen = { version = "0.60.1", optional = true }


[features]
default = ["build", "bindgen"] 
build = ["dep:cmake", "clone"]
no-build = ["build"]
clone = []
bindgen = ["dep:bindgen", "clone"]
