[package]
name = "libjpeg-sys"
description = "Builds and links libjpeg(-turbo)"
version = "0.1.0"
edition = "2021"
license = "MIT"
links = "libjpeg"

[dependencies]

[build-dependencies]
cc = { version = "1.0.73", features = ["parallel"], optioal = true }
itoa = { version = "1.0.4", optional = true }

[features]
default = ["build"] 
build = ["dep:cc", "dep:itoa", "clone"]
no-build = []
clone = []
